name: create-tag-from-cargo-toml
description: >-
  Create and push a Git tag (which can be used to trigger a release workflow) 
  from the version in the Rust manifest file (cargo.toml)

inputs:
  path-to-cargo-toml:
    description: >-
      The (relative) path (in the source repository) to the `Cargo.toml` file to generate documentation for. If not specified, assumes `Cargo.toml`.
    required: false

runs:
  using: composite
  steps:
    - name: Checkout this repository
      uses: actions/checkout@v3
      with:
        clean: false
        repository: "aisrael/create-tag-from-cargo-toml"
        sparse-checkout: |
          create-tag.rb
          Gemfile
          Gemfile.lock
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true
    - shell: bash
      env:
        PATH_TO_CARGO_TOML: ${{ inputs.path-to-cargo-toml }}
      run: |
        set -x
        pwd
        ls -l
        bundle exec -- ruby create-tag.rb "${PATH_TO_CARGO_TOML}"

branding:
  icon: book-open
  color: purple
